### ISSUE TITLE
Haxe < 4.1 compatibility

### ISSUE THREAD

**Issue by jonasmalacofilho** [haxe-utest/utest#104]
Has support for Haxe < 4.1 been dropped?  Was it intentional?  :smiley: 

![Screenshot from 2020-07-24 16-03-00](https://user-images.githubusercontent.com/1832496/88426832-37b54000-cdc8-11ea-9726-f91e29a04436.png)

P.S. Some of these failures may be from tooling issues, but it's definitively broken on 3.4.7 (and possibly 4.0.5).
P.P.S. This popped up on the record-macros tests.

**Comment by RealyUniqueName** [comment]
My bad.
Fixed and released.
Thanks for the report!

**Comment by jonasmalacofilho** [comment]
Travis is still failing (due, it seems, incompatible system dependencies), but record-macros was already able to use the new release and pass its tests.

Thanks : )
