### ISSUE TITLE
untyped call

### ISSUE THREAD

**Issue by profelis** [haxe-utest/utest#9]
please, add cast to haxe.ds.StringMap(IntMap) here
https://github.com/fponticelli/utest/blob/d8ab198807434549f172dc18b157ec49327eb0cf/src/utest/Assert.hx#L289-L290

dce remove IntMap.keys() and IntMap.get() methods, because doesn't find method usage.

Related to https://github.com/ciscoheat/buddy/issues/24

**Comment by ciscoheat** [comment]
It seems related, the test used to confirm the issue for Buddy hangs when targeting java:

``` haxe
Assert.same([1 => 2], [1 => 2]);
Assert.same(["a" => 1], ["a" => 1]);
```

**Comment by ciscoheat** [comment]
More specifically, it's the first line that fails.

**Comment by profelis** [comment]
In utest fails only first line, because utest use StringMap, but never IntMap

https://github.com/fponticelli/utest/blob/d8ab198807434549f172dc18b157ec49327eb0cf/src/utest/ui/common/PackageResult.hx#L90

**Comment by ciscoheat** [comment]
But only in java?

**Comment by profelis** [comment]
Hm, I don't know. Do you can attach dump and result code of IntMap.java (-D dump=pretty for dump)?

**Comment by ciscoheat** [comment]
Yes, I'll do that later. This issue really created some strange effects on different targets. Seems to have a similar problem with C++ on Linux now.

**Comment by fponticelli** [comment]
Feel free to make a PR and I will gladly merge it. Or I will have to look into it during the weekend.

**Comment by profelis** [comment]
https://github.com/fponticelli/utest/pull/10

**Comment by profelis** [comment]
@ciscoheat fix merged, you can remove temporary fix in buddy and check again!

**Comment by ciscoheat** [comment]
Problem remains, but with much better error messages after the fix. Here's what I get now:

Java

```
  should compare maps correctly (FAILED: Field not found.)
    @ DelegatingMethodAccessorImpl.java:43
    @ Method.java:483
    @ DelegatingMethodAccessorImpl.java:43
    @ Method.java:483
    @ DelegatingMethodAccessorImpl.java:43
    @ Method.java:483
    @ DelegatingMethodAccessorImpl.java:43
    @ Method.java:483
    @ DelegatingMethodAccessorImpl.java:43
    @ Method.java:483
    @ DelegatingMethodAccessorImpl.java:43
    @ Method.java:483
    @ DelegatingMethodAccessorImpl.java:43
    @ Method.java:483
    @ FutureTask.java:266
    @ ThreadPoolExecutor.java:1142
    @ ThreadPoolExecutor.java:617
```

C++

```
should compare maps correctly (FAILED: Null Function Pointer)
```

@fponticelli what do you think, something worth looking at in utest, or a deeper problem?

**Comment by fponticelli** [comment]
Is this from the first test?

``` haxe
Assert.same([1 => 2], [1 => 2]);
```

**Comment by ciscoheat** [comment]
Yes, that line gives the above errors in C++ and Java. I'm investigating exactly where it goes wrong right now.

**Comment by ciscoheat** [comment]
No wait, I was using the haxelib version, not this repo. It works. Can you update haxelib please? :)

**Comment by fponticelli** [comment]
I will do it tonight for sure :)

**Comment by profelis** [comment]
@ciscoheat, Same tests 
https://github.com/fponticelli/utest/blob/master/test/utest/TestAssert.hx#L104-L107

correct completed in utest core
https://travis-ci.org/fponticelli/utest/builds/40100562

@ciscoheat, I think problem is more deeper. Share you test, dump and java classes

**Comment by ciscoheat** [comment]
@profelis I was using the wrong version, it works now.

**Comment by fponticelli** [comment]
released

**Comment by ciscoheat** [comment]
Cannot see it on http://lib.haxe.org/

**Comment by fponticelli** [comment]
Should be there for real now.

**Comment by ciscoheat** [comment]
Got it. :+1:
